#!/bin/bash
sed -i 's/import androidx.compose.material.icons.filled.Wifi/import androidx.compose.material.icons.filled.Wifi\nimport androidx.compose.material.icons.filled.Usb\nimport android.app.PendingIntent\nimport android.content.BroadcastReceiver\nimport android.content.Context\nimport android.content.Intent\nimport android.content.IntentFilter\nimport android.hardware.usb.UsbConstants\nimport android.hardware.usb.UsbDevice\nimport android.hardware.usb.UsbManager\nimport android.widget.Toast\nimport androidx.compose.runtime.DisposableEffect\nimport androidx.compose.ui.platform.LocalContext/g' /app/applet/app/src/main/java/com/yangyx/adbhelper/ui/screens/ConnectScreen.kt

awk '
/    var pairCode by remember { mutableStateOf/ {
    print
    print "    val context = LocalContext.current"
    print "    val ACTION_USB_PERMISSION = \"com.yangyx.adbhelper.USB_PERMISSION\""
    print ""
    print "    DisposableEffect(context) {"
    print "        val usbReceiver = object : BroadcastReceiver() {"
    print "            override fun onReceive(context: Context, intent: Intent) {"
    print "                if (ACTION_USB_PERMISSION == intent.action) {"
    print "                    synchronized(this) {"
    print "                        val device: UsbDevice? = intent.getParcelableExtra(UsbManager.EXTRA_DEVICE)"
    print "                        if (intent.getBooleanExtra(UsbManager.EXTRA_PERMISSION_GRANTED, false)) {"
    print "                            device?.apply {"
    print "                                val usbManager = context.getSystemService(Context.USB_SERVICE) as UsbManager"
    print "                                var adbInterface: android.hardware.usb.UsbInterface? = null"
    print "                                for (i in 0 until device.interfaceCount) {"
    print "                                    val intf = device.getInterface(i)"
    print "                                    if (intf.interfaceClass == UsbConstants.USB_CLASS_VENDOR_SPEC &&"
    print "                                        intf.interfaceSubclass == 0x42 &&"
    print "                                        intf.interfaceProtocol == 0x01) {"
    print "                                        adbInterface = intf"
    print "                                        break"
    print "                                    }"
    print "                                }"
    print "                                if (adbInterface != null) {"
    print "                                    var endpointIn: android.hardware.usb.UsbEndpoint? = null"
    print "                                    var endpointOut: android.hardware.usb.UsbEndpoint? = null"
    print "                                    for (i in 0 until adbInterface.endpointCount) {"
    print "                                        val ep = adbInterface.getEndpoint(i)"
    print "                                        if (ep.direction == UsbConstants.USB_DIR_IN) {"
    print "                                            endpointIn = ep"
    print "                                        } else if (ep.direction == UsbConstants.USB_DIR_OUT) {"
    print "                                            endpointOut = ep"
    print "                                        }"
    print "                                    }"
    print "                                    if (endpointIn != null && endpointOut != null) {"
    print "                                        val connection = usbManager.openDevice(device)"
    print "                                        if (connection != null) {"
    print "                                            connection.claimInterface(adbInterface, true)"
    print "                                            viewModel.connectUsb(connection, endpointIn, endpointOut)"
    print "                                            onNavigateToRemote()"
    print "                                        } else {"
    print "                                            Toast.makeText(context, \"无法打开 USB 设备\", Toast.LENGTH_SHORT).show()"
    print "                                        }"
    print "                                    }"
    print "                                } else {"
    print "                                    Toast.makeText(context, \"此设备不是支持 ADB 的设备\", Toast.LENGTH_SHORT).show()"
    print "                                }"
    print "                            }"
    print "                        } else {"
    print "                            Toast.makeText(context, \"用户拒绝了 USB 权限\", Toast.LENGTH_SHORT).show()"
    print "                        }"
    print "                    }"
    print "                }"
    print "            }"
    print "        }"
    print "        val filter = IntentFilter(ACTION_USB_PERMISSION)"
    print "        if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.TIRAMISU) {"
    print "            context.registerReceiver(usbReceiver, filter, Context.RECEIVER_NOT_EXPORTED)"
    print "        } else {"
    print "            context.registerReceiver(usbReceiver, filter)"
    print "        }"
    print "        onDispose {"
    print "            context.unregisterReceiver(usbReceiver)"
    print "        }"
    print "    }"
    next
}
{ print }
' /app/applet/app/src/main/java/com/yangyx/adbhelper/ui/screens/ConnectScreen.kt > /tmp/ConnectScreen.kt
mv /tmp/ConnectScreen.kt /app/applet/app/src/main/java/com/yangyx/adbhelper/ui/screens/ConnectScreen.kt

awk '
/                                Text\("一键连接", fontWeight = FontWeight.Bold\)/ {
    print
    print "                            }"
    print "                        }"
    print "                        Button("
    print "                            onClick = {"
    print "                                val usbManager = context.getSystemService(Context.USB_SERVICE) as UsbManager"
    print "                                val deviceList = usbManager.deviceList"
    print "                                var foundDevice: UsbDevice? = null"
    print "                                for (device in deviceList.values) {"
    print "                                    for (i in 0 until device.interfaceCount) {"
    print "                                        val intf = device.getInterface(i)"
    print "                                        if (intf.interfaceClass == UsbConstants.USB_CLASS_VENDOR_SPEC &&"
    print "                                            intf.interfaceSubclass == 0x42 &&"
    print "                                            intf.interfaceProtocol == 0x01) {"
    print "                                            foundDevice = device"
    print "                                            break"
    print "                                        }"
    print "                                    }"
    print "                                }"
    print "                                if (foundDevice != null) {"
    print "                                    val permissionIntent = PendingIntent.getBroadcast("
    print "                                        context, 0, Intent(ACTION_USB_PERMISSION),"
    print "                                        PendingIntent.FLAG_MUTABLE or PendingIntent.FLAG_UPDATE_CURRENT"
    print "                                    )"
    print "                                    usbManager.requestPermission(foundDevice, permissionIntent)"
    print "                                } else {"
    print "                                    Toast.makeText(context, \"未找到通过 OTG 连接的 ADB 设备\", Toast.LENGTH_SHORT).show()"
    print "                                }"
    print "                            },"
    print "                            enabled = connectionState !is ConnectionState.Connecting,"
    print "                            shape = RoundedCornerShape(14.dp),"
    print "                            colors = ButtonDefaults.buttonColors(containerColor = MaterialTheme.colorScheme.secondary),"
    print "                            modifier = Modifier.height(50.dp)"
    print "                        ) {"
    print "                            Icon(Icons.Default.Usb, contentDescription = \"OTG\")"
    print "                            Spacer(modifier = Modifier.width(4.dp))"
    print "                            Text(\"OTG直连\", fontWeight = FontWeight.Bold)"
    next
}
{ print }
' /app/applet/app/src/main/java/com/yangyx/adbhelper/ui/screens/ConnectScreen.kt > /tmp/ConnectScreen.kt
mv /tmp/ConnectScreen.kt /app/applet/app/src/main/java/com/yangyx/adbhelper/ui/screens/ConnectScreen.kt
